
services:
  polybot:
    image: ${POLYBOT_IMG_NAME}
    container_name: telegram_bot
    ports:
      - "8443:8443"
    environment:
      - TELEGRAM_APP_URL=${TELEGRAM_APP_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BUCKET_NAME=${BUCKET_NAME}
    depends_on:
      - yolo5
      - mongo1
      - mongo2
      - mongo3
    networks:
      - app_network
    volumes:
      -  /home/hadeelarshed/.aws/credentials:/root/.aws/credentials

  yolo5:
    image: ${YOLO5_IMG_NAME}
    container_name: yolo5
    ports:
      - "8081:8081"
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - app_network
    volumes:
      - /home/hadeelarshed/.aws/credentials:/root/.aws/credentials

  mongo1:
    image: mongo:4
    container_name: mongo1
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip" , "localhost,mongo1"]
    networks:
      - app_network

  mongo2:
    image: mongo:4
    container_name: mongo2
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip" , "localhost,mongo2"]
    depends_on:
      - mongo1
    networks:
      - app_network

  mongo3:
    image: mongo:4
    container_name: mongo3
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip" , "localhost,mongo3"]
    depends_on:
      - mongo1
    networks:
      - app_network

networks:
  app_network:
    driver: bridge